--Creating the patients table

  CREATE TABLE "HAGUMA07"."PATIENTS" 
   (	"PATIENT_ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"BIRTH_DATE" DATE NOT NULL ENABLE, 
	"GENDER" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"MEDICAL_INSURANCE" VARCHAR2(50 BYTE), 
	 CHECK (gender IN ('M','F','Other')) ENABLE, 
	 CONSTRAINT "PK_PATIENTS" PRIMARY KEY ("PATIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UQ_PATIENTS_PHONE" UNIQUE ("PHONE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "HAGUMA07"."TRG_RESTRICT_PATIENT_CHANGES" 
BEFORE INSERT OR UPDATE OR DELETE ON patients
FOR EACH ROW
DECLARE
    v_restricted BOOLEAN;
    v_employee_id NUMBER;
    v_audit_id NUMBER;
    v_error_message VARCHAR2(500);
BEGIN
    -- Simulate employee ID (in real system, this would come from session/application)
    -- Using patient_id as placeholder for employee_id in this demo
    v_employee_id := NVL(:NEW.patient_id, :OLD.patient_id);

    -- Check restriction
    v_restricted := is_restricted_day();

    IF v_restricted THEN
        -- Build error message
        v_error_message := 'Employee operations not permitted on ';

        IF TO_CHAR(SYSDATE, 'D') IN ('2','3','4','5','6') THEN
            v_error_message := v_error_message || 'weekdays';
        ELSE
            v_error_message := v_error_message || 'weekends';
        END IF;

        -- Check if holiday
        BEGIN
            SELECT 'Y' INTO v_error_message
            FROM system_holidays
            WHERE holiday_date = TRUNC(SYSDATE)
            AND ROWNUM = 1;

            v_error_message := 'Employee operations not permitted on public holidays';
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                NULL;
        END;

        -- Log the attempt
        v_audit_id := log_restriction_audit(
            p_table_name => 'PATIENTS',
            p_operation_type => 
                CASE 
                    WHEN INSERTING THEN 'INSERT'
                    WHEN UPDATING THEN 'UPDATE'
                    WHEN DELETING THEN 'DELETE'
                END,
            p_employee_id => v_employee_id,
            p_restriction_applied => 'Y',
            p_error_message => v_error_message
        );

        -- Raise application error
        RAISE_APPLICATION_ERROR(-20901, 
            v_error_message || '. ' ||
            'Audit ID: ' || v_audit_id || '. ' ||
            'Date: ' || TO_CHAR(SYSDATE, 'DD-MON-YYYY')
        );
    ELSE
        -- Log allowed operation
        v_audit_id := log_restriction_audit(
            p_table_name => 'PATIENTS',
            p_operation_type => 
                CASE 
                    WHEN INSERTING THEN 'INSERT'
                    WHEN UPDATING THEN 'UPDATE'
                    WHEN DELETING THEN 'DELETE'
                END,
            p_employee_id => v_employee_id,
            p_restriction_applied => 'N',
            p_error_message => NULL
        );
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        -- Re-raise the exception
        RAISE;
END trg_restrict_patient_changes;

/
ALTER TRIGGER "HAGUMA07"."TRG_RESTRICT_PATIENT_CHANGES" ENABLE;



-- Creating patient queue table

  CREATE TABLE "HAGUMA07"."PATIENT_QUEUE" 
   (	"QUEUE_ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PATIENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ROOM_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"QUEUE_POSITION" NUMBER(5,0) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'waiting', 
	"TIME_ENTERED_QUEUE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CHECK_IN_TIME" TIMESTAMP (6), 
	"CHECK_OUT_TIME" TIMESTAMP (6), 
	 CHECK (status IN ('waiting','in-progress','completed','skipped')) ENABLE, 
	 CONSTRAINT "CK_PQ_TIME_ORDER" CHECK (
    (check_in_time IS NULL OR check_out_time IS NULL) OR
    (check_in_time <= check_out_time)
  ) ENABLE, 
	 CONSTRAINT "PK_PATIENT_QUEUE" PRIMARY KEY ("QUEUE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UQ_PQ_ROOM_POS" UNIQUE ("ROOM_ID", "QUEUE_POSITION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_PQ_PATIENT" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "HAGUMA07"."PATIENTS" ("PATIENT_ID") ENABLE, 
	 CONSTRAINT "FK_PQ_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "HAGUMA07"."SERVICE_ROOMS" ("ROOM_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "HAGUMA07"."TRG_VALIDATE_QUEUE_TIMES" 
BEFORE INSERT OR UPDATE ON patient_queue
FOR EACH ROW
BEGIN
    -- Check time order constraint
    IF :NEW.check_in_time IS NOT NULL AND :NEW.check_out_time IS NOT NULL THEN
        IF :NEW.check_in_time > :NEW.check_out_time THEN
            RAISE_APPLICATION_ERROR(-20010, 'check_in_time cannot be after check_out_time');
        END IF;
    END IF;

    -- Auto-set time_entered_queue if null
    IF INSERTING AND :NEW.time_entered_queue IS NULL THEN
        :NEW.time_entered_queue := SYSTIMESTAMP;
    END IF;
END;

/
ALTER TRIGGER "HAGUMA07"."TRG_VALIDATE_QUEUE_TIMES" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "HAGUMA07"."TRG_LOG_PATIENT_MOVEMENT" 
AFTER INSERT OR UPDATE ON patient_queue
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    -- Determine action based on status change
    IF INSERTING THEN
        v_action := 'queued';
    ELSIF UPDATING THEN
        IF :OLD.status != :NEW.status THEN
            CASE :NEW.status
                WHEN 'in-progress' THEN v_action := 'entered';
                WHEN 'completed' THEN v_action := 'exited';
                WHEN 'skipped' THEN v_action := 'redirected';
                ELSE v_action := 'updated';
            END CASE;
        ELSE
            RETURN; -- No status change, no logging needed
        END IF;
    END IF;

    -- Insert movement log
    INSERT INTO movement_log (move_id, patient_id, room_id, move_time, action, queue_id)
    VALUES (move_seq.NEXTVAL, :NEW.patient_id, :NEW.room_id, SYSTIMESTAMP, v_action, :NEW.queue_id);

EXCEPTION
    WHEN OTHERS THEN
        NULL; -- Don't fail the main operation if logging fails
END;

/
ALTER TRIGGER "HAGUMA07"."TRG_LOG_PATIENT_MOVEMENT" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "HAGUMA07"."TRG_RESTRICT_QUEUE_CHANGES" 
BEFORE INSERT OR UPDATE OR DELETE ON patient_queue
FOR EACH ROW
DECLARE
    v_restricted BOOLEAN;
    v_employee_id NUMBER;
    v_audit_id NUMBER;
BEGIN
    -- IMPORTANT EXCEPTION: Allow status updates even on restricted days
    -- This ensures patient flow isn't disrupted
    IF UPDATING AND :OLD.status IS NOT NULL AND :NEW.status IS NOT NULL THEN
        -- Allow status changes (like updating from 'waiting' to 'completed')
        RETURN;
    END IF;

    -- Get employee ID (using patient_id as placeholder)
    v_employee_id := NVL(:NEW.patient_id, :OLD.patient_id);

    -- Check restriction
    v_restricted := is_restricted_day();

    IF v_restricted THEN
        -- Log the attempt
        v_audit_id := log_restriction_audit(
            p_table_name => 'PATIENT_QUEUE',
            p_operation_type => 
                CASE 
                    WHEN INSERTING THEN 'INSERT'
                    WHEN UPDATING THEN 'UPDATE'
                    WHEN DELETING THEN 'DELETE'
                END,
            p_employee_id => v_employee_id,
            p_restriction_applied => 'Y',
            p_error_message => 'Queue operations restricted on weekdays/holidays'
        );

        -- Raise error
        RAISE_APPLICATION_ERROR(-20903, 
            'Employee queue operations not permitted on weekdays or holidays. ' ||
            'Exception: Status updates are allowed. ' ||
            'Audit ID: ' || v_audit_id
        );
    ELSE
        -- Log allowed operation
        v_audit_id := log_restriction_audit(
            p_table_name => 'PATIENT_QUEUE',
            p_operation_type => 
                CASE 
                    WHEN INSERTING THEN 'INSERT'
                    WHEN UPDATING THEN 'UPDATE'
                    WHEN DELETING THEN 'DELETE'
                END,
            p_employee_id => v_employee_id,
            p_restriction_applied => 'N',
            p_error_message => NULL
        );
    END IF;

END trg_restrict_queue_changes;

/
ALTER TRIGGER "HAGUMA07"."TRG_RESTRICT_QUEUE_CHANGES" ENABLE;


--Creating staff users table


  CREATE TABLE "HAGUMA07"."STAFF_USERS" 
   (	"STAFF_ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ROOM_ID" NUMBER(10,0), 
	 CONSTRAINT "PK_STAFF_USERS" PRIMARY KEY ("STAFF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UQ_STAFF_USERS_USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_STAFF_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "HAGUMA07"."SERVICE_ROOMS" ("ROOM_ID") ON DELETE SET NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "HAGUMA07"."TRG_RESTRICT_STAFF_CHANGES" 
FOR INSERT OR UPDATE OR DELETE ON staff_users
COMPOUND TRIGGER

    -- Type declarations
    TYPE t_audit_rec IS RECORD (
        table_name VARCHAR2(50),
        operation_type VARCHAR2(10),
        employee_id NUMBER,
        staff_id NUMBER,
        restriction_applied CHAR(1),
        error_message VARCHAR2(500)
    );

    TYPE t_audit_table IS TABLE OF t_audit_rec;
    v_audit_data t_audit_table := t_audit_table();

    -- Before statement section
    BEFORE STATEMENT IS
    BEGIN
        v_audit_data.DELETE; -- Clear collection for new statement
    END BEFORE STATEMENT;

    -- Before each row section
    BEFORE EACH ROW IS
        v_restricted BOOLEAN;
    BEGIN
        -- Check restriction
        v_restricted := is_restricted_day();

        IF v_restricted THEN
            -- Add to audit collection
            v_audit_data.EXTEND;
            v_audit_data(v_audit_data.LAST).table_name := 'STAFF_USERS';
            v_audit_data(v_audit_data.LAST).operation_type := 
                CASE 
                    WHEN INSERTING THEN 'INSERT'
                    WHEN UPDATING THEN 'UPDATE'
                    WHEN DELETING THEN 'DELETE'
                END;
            v_audit_data(v_audit_data.LAST).employee_id := :NEW.staff_id;
            v_audit_data(v_audit_data.LAST).staff_id := :NEW.staff_id;
            v_audit_data(v_audit_data.LAST).restriction_applied := 'Y';
            v_audit_data(v_audit_data.LAST).error_message := 
                'Staff user modifications restricted on weekdays/holidays';

            -- Raise error immediately
            RAISE_APPLICATION_ERROR(-20904, 
                'Staff user operations not permitted on weekdays or holidays. ' ||
                'Operation: ' || v_audit_data(v_audit_data.LAST).operation_type || ' ' ||
                'Staff ID: ' || v_audit_data(v_audit_data.LAST).staff_id
            );
        ELSE
            -- Add allowed operation to collection
            v_audit_data.EXTEND;
            v_audit_data(v_audit_data.LAST).table_name := 'STAFF_USERS';
            v_audit_data(v_audit_data.LAST).operation_type := 
                CASE 
                    WHEN INSERTING THEN 'INSERT'
                    WHEN UPDATING THEN 'UPDATE'
                    WHEN DELETING THEN 'DELETE'
                END;
            v_audit_data(v_audit_data.LAST).employee_id := :NEW.staff_id;
            v_audit_data(v_audit_data.LAST).staff_id := :NEW.staff_id;
            v_audit_data(v_audit_data.LAST).restriction_applied := 'N';
            v_audit_data(v_audit_data.LAST).error_message := NULL;
        END IF;
    END BEFORE EACH ROW;

    -- After statement section (for logging allowed operations)
    AFTER STATEMENT IS
        v_audit_id NUMBER;
    BEGIN
        -- Log all non-restricted operations
        FOR i IN 1..v_audit_data.COUNT LOOP
            IF v_audit_data(i).restriction_applied = 'N' THEN
                v_audit_id := log_restriction_audit(
                    p_table_name => v_audit_data(i).table_name,
                    p_operation_type => v_audit_data(i).operation_type,
                    p_employee_id => v_audit_data(i).employee_id,
                    p_restriction_applied => v_audit_data(i).restriction_applied,
                    p_error_message => v_audit_data(i).error_message
                );
            END IF;
        END LOOP;
    END AFTER STATEMENT;

END trg_restrict_staff_changes;

/
ALTER TRIGGER "HAGUMA07"."TRG_RESTRICT_STAFF_CHANGES" ENABLE;

-- Creating the service request table


  CREATE TABLE "HAGUMA07"."SERVICE_REQUESTS" 
   (	"SERVICE_ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PATIENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ROOM_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SERVICE_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PRIORITY" VARCHAR2(10 BYTE) DEFAULT 'medium', 
	"SERVICE_STATUS" VARCHAR2(20 BYTE) DEFAULT 'pending', 
	"REQUESTED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 CHECK (priority IN ('low','medium','high')) ENABLE, 
	 CHECK (service_status IN ('pending','active','completed','cancelled')) ENABLE, 
	 CONSTRAINT "PK_SERVICE_REQUESTS" PRIMARY KEY ("SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_SR_PATIENT" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "HAGUMA07"."PATIENTS" ("PATIENT_ID") ENABLE, 
	 CONSTRAINT "FK_SR_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "HAGUMA07"."SERVICE_ROOMS" ("ROOM_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "HAGUMA07"."TRG_SERVICE_REQUEST_TIMESTAMP" 
BEFORE INSERT ON service_requests
FOR EACH ROW
BEGIN
    IF :NEW.requested_at IS NULL THEN
        :NEW.requested_at := SYSTIMESTAMP;
    END IF;
END;

/
ALTER TRIGGER "HAGUMA07"."TRG_SERVICE_REQUEST_TIMESTAMP" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "HAGUMA07"."TRG_RESTRICT_SERVICE_CHANGES" 
BEFORE INSERT OR UPDATE OR DELETE ON service_requests
FOR EACH ROW
DECLARE
    v_restricted BOOLEAN;
    v_employee_id NUMBER;
    v_audit_id NUMBER;
BEGIN
    -- Get employee ID (using patient_id as placeholder)
    v_employee_id := NVL(:NEW.patient_id, :OLD.patient_id);

    -- Check restriction
    v_restricted := is_restricted_day();

    IF v_restricted THEN
        -- Log the attempt
        v_audit_id := log_restriction_audit(
            p_table_name => 'SERVICE_REQUESTS',
            p_operation_type => 
                CASE 
                    WHEN INSERTING THEN 'INSERT'
                    WHEN UPDATING THEN 'UPDATE'
                    WHEN DELETING THEN 'DELETE'
                END,
            p_employee_id => v_employee_id,
            p_restriction_applied => 'Y',
            p_error_message => 'Operation restricted on weekdays/holidays'
        );

        -- Raise error
        RAISE_APPLICATION_ERROR(-20902, 
            'Employee operations on SERVICE_REQUESTS not permitted on weekdays or holidays. ' ||
            'Audit ID: ' || v_audit_id
        );
    ELSE
        -- Log allowed operation
        v_audit_id := log_restriction_audit(
            p_table_name => 'SERVICE_REQUESTS',
            p_operation_type => 
                CASE 
                    WHEN INSERTING THEN 'INSERT'
                    WHEN UPDATING THEN 'UPDATE'
                    WHEN DELETING THEN 'DELETE'
                END,
            p_employee_id => v_employee_id,
            p_restriction_applied => 'N',
            p_error_message => NULL
        );
    END IF;

END trg_restrict_service_changes;

/
ALTER TRIGGER "HAGUMA07"."TRG_RESTRICT_SERVICE_CHANGES" ENABLE;

-- Creating movement log table


  CREATE TABLE "HAGUMA07"."MOVEMENT_LOG" 
   (	"MOVE_ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PATIENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ROOM_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"MOVE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"ACTION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"QUEUE_ID" NUMBER(10,0), 
	"STAFF_ID" NUMBER(10,0), 
	 CHECK (action IN ('entered','exited','redirected')) ENABLE, 
	 CONSTRAINT "PK_MOVEMENT_LOG" PRIMARY KEY ("MOVE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ML_PATIENT" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "HAGUMA07"."PATIENTS" ("PATIENT_ID") ENABLE, 
	 CONSTRAINT "FK_ML_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "HAGUMA07"."SERVICE_ROOMS" ("ROOM_ID") ENABLE, 
	 CONSTRAINT "FK_ML_QUEUE" FOREIGN KEY ("QUEUE_ID")
	  REFERENCES "HAGUMA07"."PATIENT_QUEUE" ("QUEUE_ID") ENABLE, 
	 CONSTRAINT "FK_ML_STAFF" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "HAGUMA07"."STAFF_USERS" ("STAFF_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- Creating service rooms table


  CREATE TABLE "HAGUMA07"."SERVICE_ROOMS" 
   (	"ROOM_ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ROOM_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ROOM_TYPE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FLOOR" NUMBER(2,0), 
	"ROOM_DESCRIPTION" VARCHAR2(200 BYTE), 
	 CONSTRAINT "PK_SERVICE_ROOMS" PRIMARY KEY ("ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UQ_SERVICE_ROOMS_NAME" UNIQUE ("ROOM_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- Creating the system holidays table


  CREATE TABLE "HAGUMA07"."SYSTEM_HOLIDAYS" 
   (	"HOLIDAY_ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"HOLIDAY_DATE" DATE NOT NULL ENABLE, 
	"HOLIDAY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"IS_RECURRING" CHAR(1 BYTE) DEFAULT 'N', 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATED_BY" VARCHAR2(50 BYTE) DEFAULT USER, 
	 CHECK (is_recurring IN ('Y', 'N')) ENABLE, 
	 PRIMARY KEY ("HOLIDAY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UQ_HOLIDAY_DATE" UNIQUE ("HOLIDAY_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


-- Creating employee restriction audit table


  CREATE TABLE "HAGUMA07"."EMPLOYEE_RESTRICTION_AUDIT" 
   (	"AUDIT_ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"OPERATION_TYPE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"EMPLOYEE_ID" NUMBER(10,0), 
	"ATTEMPTED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"ATTEMPT_DAY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IS_WEEKDAY" CHAR(1 BYTE) DEFAULT 'Y', 
	"IS_HOLIDAY" CHAR(1 BYTE) DEFAULT 'N', 
	"RESTRICTION_APPLIED" CHAR(1 BYTE) DEFAULT 'N', 
	"ERROR_MESSAGE" VARCHAR2(500 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE) DEFAULT USER, 
	"IP_ADDRESS" VARCHAR2(50 BYTE) DEFAULT SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 
	"SESSION_ID" VARCHAR2(50 BYTE) DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID'), 
	 CHECK (operation_type IN ('INSERT', 'UPDATE', 'DELETE')) ENABLE, 
	 CHECK (is_weekday IN ('Y', 'N')) ENABLE, 
	 CHECK (is_holiday IN ('Y', 'N')) ENABLE, 
	 CHECK (restriction_applied IN ('Y', 'N')) ENABLE, 
	 PRIMARY KEY ("AUDIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE INDEX "HAGUMA07"."IDX_AUDIT_DATE" ON "HAGUMA07"."EMPLOYEE_RESTRICTION_AUDIT" ("ATTEMPTED_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE INDEX "HAGUMA07"."IDX_AUDIT_TABLE" ON "HAGUMA07"."EMPLOYEE_RESTRICTION_AUDIT" ("TABLE_NAME", "OPERATION_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE INDEX "HAGUMA07"."IDX_AUDIT_RESTRICTION" ON "HAGUMA07"."EMPLOYEE_RESTRICTION_AUDIT" ("RESTRICTION_APPLIED") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

